# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec2470206672f396fe31d0190c21cd3fb351b2be856d6758a9165da0e407399ba4930aa027c880bbf24c878f081b998df4a475506bf1f73455890e4e085dd390

test:
  secret_key_base: 170200b3250d0f29d74e5f4524013377b062f1f3e5050b813403f602a355c50589feee7f6cf4500731811f022ebc89efd82b79ee6cbfc843742ec0674f11b19b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
